### ISSUE TITLE
Planung Abfrage-Algorithmus

### ISSUE THREAD

**Issue by l4uchbr0t** [atalantus/Wokabel-App#11]
## Task zur User Story #9 bzw. #4
- Überlegung über das Vorgehen
- Pseudocode und Beschreibung

**Comment by Direcx** [comment]
hat das wirklich eine so viel höhere Priorität, als die anderen Tasks? und evtl wäre eine genauere Beschreibung noch passender, weil momentan ist das Thema nicht so ganz ersichtlich. Soll dieser Task beschreiben, dass man den Algorithmus planen und beschreiben soll?

**Comment by Reiswaffl** [comment]
Attribute:
private ArrayList<Vocable> randomsortedWok;
Methoden:
randomizing Method:
-	temporäre ArrayList mit (erst nur gewünschte ArrayList einlesen)
-	 Vokabeln nach Leveln einfügen (Level 2: 2x enthalten, etc..)
-	 und dann zufällig sortieren
aktuelle Wokabel geben: 
-	aktuelle Wokabel ist immer die erste Vokabel in der ArrayList (index 0)
-	Methode, welche die aktuelle Vokabel ausgibt.
handlingAnswer : 
-	boolean Eingabe (ob richtig oder falsch)
-	wenn richtig
o	aktuelle Wokabel aus Liste löschen 
o	Level Abstufen (max. -2)
-	wenn falsch
o	aktuelle Wokabel hinten nochmal einfügen 
o	aktuelle Wokabel vorne aus Liste löschen
o	 Level Hochstufen (max. 6)
