### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by pierrelouisSuckrow** [atalantus/Wokabel-App#18]
## Task zur User Story #17 
Home Screen mit Logo 
Mögliche Anmelde Möglichkeit 
Bei Drücken des mittigen Button kommt man zum nächsten Screen.

**Comment by atalantus** [comment]
Dieser Screen sollte nur beim allerersten Start der App angezeigt werden.
Da gibt der User dann seinen Namen ein und fertig.

Beim zukünftigen starten wäre dieser screen sinnlos. Deswegen sollte der User direkt zum Language Select screen weitergeleitet werden.


Aus diesen Gründen finde ich den Namen der View falsch. Ich fände **Welcome** besser als **Home**.
