### ISSUE TITLE
Erste Implementierung

### ISSUE THREAD

**Issue by JonahKr** [atalantus/Wokabel-App#27]
## Task zur User Story *#5*

Implementierung einer Grundlegenden Datenbank mit mindestens einer Tabelle.

**Comment by JonahKr** [comment]
Die Implementierung ist soweit fertig, was fehlt ist die Verknüpfung zum Rest

**Comment by atalantus** [comment]
Wenn die Implementierung fertig ist und funktioniert könnt ihr ne pull request machen.

**Comment by JonahKr** [comment]
@atalantus was fehlt ist wie gesagt die verknüpfung. soll ich trotzdem mergen?
