### ISSUE TITLE
Vokabel Presets

### ISSUE THREAD

**Issue by JonahKr** [atalantus/Wokabel-App#48]
## Task zur User Story *#5*

Bei erststart der Applikation wird ein fertiger Datensatz in die Datenbank eingetragen.
Bei sonstigem starten, wird gekuckt, ob in der Datenbank Daten vorhanden sind. 
Wenn nicht, wird der Datensatz hinzugefügt, anderfalls nicht.

**Comment by JonahKr** [comment]
#46

**Comment by atalantus** [comment]
Hierzu gehört doch dann auch der #49 Task oder?

So hab ich diese Excel Tabelle verstanden.

**Comment by atalantus** [comment]
Ich würde vorschlagen wir implementieren das ganze als `.json` Ressource wie in der [**sunflower sample app**](https://github.com/googlesamples/android-sunflower/blob/master/app/src/main/assets/plants.json)

Dann können wir die laden wann wir wollen.

**Comment by atalantus** [comment]
Wenn ihr wissen wollt, wo ihr das mit dem Erststart herausfinden könnt, guckt mal [hier vorbei](https://github.com/atalantus/Wokabel-App/wiki/Dokumentation-%7C-Activities#launch-activity).

**Comment by JonahKr** [comment]
ich weiß wie das funktioniert -_-
