### ISSUE TITLE
DEPRECATED: Daten aus Excel importieren

### ISSUE THREAD

**Issue by SamuelRoettgermann** [atalantus/Wokabel-App#49]
## Task zur User Story *#5*
*Hinzufügen einer Möglichkeit des Importierens von Daten aus Excel in die Datenbank*

**Comment by SamuelRoettgermann** [comment]
http://www.vogella.com/tutorials/JavaExcel/article.html -> Kapitel 2 ist hierfür unwichtig, da wir in dieser Task nur readen (lesen) und nicht writen (schreiben) müssen

**Comment by SamuelRoettgermann** [comment]
https://stackoverflow.com/questions/1516144/how-to-read-and-write-excel-file#

**Comment by SamuelRoettgermann** [comment]
http://poi.apache.org/spreadsheet/index.html
http://poi.apache.org/spreadsheet/how-to.html

Sehr gute Dokumentation und Erklärung (auf Englisch) wie die Implementation aussieht bei verschiedenen Fällen, allerdings habe ich noch nicht ganz durchgeblickt, welches jetzt für unser Projekt der relevante Code ist.

**Comment by atalantus** [comment]
Also so wie sich das hier für mich liest musst du aufpassen. Ich glaube nicht, dass wir dieses Excel Sheet mit den Vokabeln aktiv in die App einbinden sollten (So dass man daraus lesen und darin schreiben kann).
Um Vokabeln zu speichern haben wir ja schließlich die Datenbank. Die Vokabeln in einer Datenbank zu speichern hat sehr, sehr viele Vorteile im Gegensatz zu so einem Excel-Sheet.

Also es kann auch sein, dass ich das jetzt falsch verstehe, aber ich dachte das dieses Excel-Sheet nur für Beispiel Daten steht, die wir am Anfang mal reinladen können?

**Comment by atalantus** [comment]
#48
