### ISSUE TITLE
Abfrage-Algorithmus

### ISSUE THREAD

**Issue by l4uchbr0t** [atalantus/Wokabel-App#9]
Der Algorithmus entscheidet über die Reihenfolge der Vokabeln. Vokablen, bei denen der Nutzer nicht so gut ist werden bei einer Abfrage mehrfach Abgefragt. Welche, bei denen der Nutzer gut ist, werden nicht immer abgefragt.

**Comment by atalantus** [comment]
Sicher dass das eine eigene **User Story** sein soll?
Wir haben ja quasi #4 als User Story für die Abfrage oder?

Ist das vielleicht eher als `Task` gemeint? (Wenn ja dann `Task` Label anstatt `UserStory`)
